# ============= Engine stepper ================

[engine.stepper]
odeSolver = "runge_kutta_dopri"
sensorsUpdatePeriod = 0.0
controllerUpdatePeriod = 0.0

# =============== Flexibilities ===============

[robot.model.dynamics]
enableFlexibility = false

# ================== Motors ===================

[robot.motors.PendulumJoint]
velocityLimitFromUrdf = false
effortLimitFromUrdf = false
enableBacklash = false
enableFriction = false
enableArmature = false
enableVelocityLimit = false
