# ============= Engine stepper ================

[engine.stepper]
odeSolver = "runge_kutta_dopri"

# =============== Flexibilities ===============

[robot.model.dynamics]
enableFlexibility = false

# ================== Motors ===================

[robot.motors.PendulumJoint]
enableBacklash = false
enableFriction = false
enableArmature = false
